apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: local-example
  name: local-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-example
  template:
    metadata:
      labels:
        app: local-example
    spec:
      containers:
      - image: local/example
        name: example
